services:
  app:
    image: hello-front-dev
    build:
      # The context will pick this directory as the "build context"
      context: .
      # This will simply tell which dockerfile to read
      dockerfile: dev.Dockerfile
    volumes:
      # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
      - ./:/usr/src/app
    ports:
      - 5173:5173
      # This will name the container hello-front-dev
    container_name: hello-front-dev