services:
  app:
    container_name: front_container_dev
    image: todo-front-dev
    build:
      # The context will pick this directory as the "build context"
      context: .
      # This will simply tell which dockerfile to read
      dockerfile: dev.Dockerfile
    volumes:
      # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
      - ./:/usr/src/app
    ports:
      # 3210 access outside container
      # 5173 access inside container
      - 3210:5173
      # This will name the container hello-front-dev
  #debug-helper:
  #  image: busybox

  nginx:
    image: nginx:1.20.1
    volumes:
      # ro declares that the volume will be read-only
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      # wait for the frontend container to be started
      # but not garantee that service is ready for action
      - app
  # if service needs to wait another service to become ready before startup
  # app:
    # condition: service_started